#!/bin/bash
if [ -n "$1" ] ; then
    BLCSRC=$1
else
    BLCSRC=test.blc
fi

./bl2 -m manifest -o output.bc < $BLCSRC && \
llc -soft-float -mattr=+noabicalls -march=mipsel -mcpu=mips32r2 -relocation-model=static -filetype=obj output.bc || exit 1

../util/mipsel-unknown-elf-ld -O3 -obl-firmware -Truntime.ld output.o bl-runtime.a
