#!/bin/bash

PROCESSOR=32MX250F128B
NAME=bl-bootloader

if [ -z "$1" ] ; then
    XCVERSION=v1.33
else
    XCVERSION=$1
fi

export PATH=/opt/microchip/xc32/$XCVERSION/bin:$PATH

mkdir -p out-boot
cd out-boot

[ -f .error ] && rm .error

for FILE in $(find -L ../boot -type f) ; do
    case $FILE in
        *.c)
            echo "Compiling $FILE"
            (xc32-gcc -c -x c -std=gnu99 -mprocessor=$PROCESSOR -I../include $FILE || echo $FILE >> .error)&
            ;;
        *.S)
            echo "Assembling $FILE"
            (xc32-gcc -c -x assembler -mprocessor=$PROCESSOR -mno-mips16 -mno-micromips -I../include $FILE -Wa,--defsym=__MPLAB_BUILD=1,--gdwarf-2 || echo $FILE >> .error)&
            ;;
        *)
            echo "Ignoring $FILE"
            ;;
    esac
done

wait

[ -f .error ] && { echo "Error during compile. [$(cat .error)]" ; exit 1 ; }

xc32-gcc -mprocessor=$PROCESSOR -o $NAME.elf -Wl,-T../linker/bootloader.ld,--defsym=__MPLAB_BUILD=1,-Map="$NAME.map" $(find . -name '*.o') && \
xc32-bin2hex -v $NAME.elf

#[ -f $NAME.a ] && rm $NAME.a
#xc32-ar r $NAME.a *.o
