#!/bin/bash

PROCESSOR=32MX250F128B
NAME=bl-hard-runtime
USERPROGRAM=$(pwd)/../example/output.s

if [ -z "$1" ] ; then
    XCVERSION=v1.40
else
    XCVERSION=$1
fi

export PATH=/opt/microchip/xc32/$XCVERSION/bin:$PATH

mkdir -p out
cd out

[ -f .error ] && rm .error

for FILE in $(find -L ../src -type f) ; do
    case $FILE in
        *.c)
            echo "Compiling $FILE"
            (xc32-gcc -c -x c -std=gnu99 -DHARD_RUNTIME -mprocessor=$PROCESSOR -I../include $FILE || echo $FILE >> .error)&
            ;;
        *.S)
            echo "Assembling $FILE"
            (xc32-gcc -c -x assembler -DHARD_RUNTIME -mprocessor=$PROCESSOR -mno-mips16 -mno-micromips -I../include $FILE -Wa,--defsym=__MPLAB_BUILD=1,--gdwarf-2 || echo $FILE >> .error)&
            ;;
        *)
            echo "Ignoring $FILE"
            ;;
    esac
done

wait

[ -f .error ] && { echo "Error during compile. [$(cat .error)]" ; exit 1 ; }

xc32-gcc -mprocessor=$PROCESSOR -o $NAME.elf -DHARD_RUNTIME -Wl,-T../linker/hard-runtime.ld,--defsym=__MPLAB_BUILD=1,-Map="$NAME.map" $(find . -name '*.o') -I../include ../boot/exception.S ../boot/handler.c ../boot/generated/* ../boot/handler_wrapper.S $USERPROGRAM && \
xc32-bin2hex -v $NAME.elf

#[ -f $NAME.a ] && rm $NAME.a
#xc32-ar r $NAME.a *.o
